#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/common.
#
# SPDX-License-Identifier: Apache-2.0
#
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        exclude: ^common-testing/3RD-PARTY-LICENSES/
        args:
          - --wrap
          - "80"
        additional_dependencies:
          - mdformat-gfm
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        exclude: ^common-testing/3RD-PARTY-LICENSES/
